local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', function() builtin.find_files({search_dirs={'./'},}) end, { desc = 'Telescope find files' })
vim.keymap.set('n', '<leader>fg', function() builtin.live_grep({search_dirs={'./'},}) end, { desc = 'Telescope live grep' })
vim.keymap.set('n', '<leader>fb', builtin.buffers, { desc = 'Telescope buffers' })
vim.keymap.set('n', '<leader>fh', builtin.help_tags, { desc = 'Telescope help tags' })
